export const ROUTE_PATHS = {
  home: "/",
  login: "/login",
  app: "/app",
  dashboard: "/app/dashboard",
  edgeGateways: "/app/edge-gateways",
  edgeGatewayDetail: "/app/edge-gateways/:edgeGatewayId",
  machines: "/app/machines",
  machineDetail: "/app/machines/:machineId",
  tags: "/app/tags",
  tagDetail: "/app/tags/:tagId",
  tagValueHistory: "/app/tag-value-history",
  oee: "/app/oee",
  analytics: "/app/analytics",
  alerts: "/app/alerts",
  reports: "/app/reports",
  users: "/app/users",
  roles: "/app/roles",
  settings: "/app/settings",
  forbidden: "/403",
  notFound: "/404",
  serverError: "/500",
} as const
